# Deploy site to GitHub Pages and generate runtime config.json from repository secrets.
# Place your Firebase values in repository Secrets with the names below.
# Secrets required (create in repo Settings -> Secrets -> Actions):
# - FIREBASE_API_KEY
# - FIREBASE_AUTH_DOMAIN
# - FIREBASE_PROJECT_ID
# - FIREBASE_STORAGE_BUCKET
# - FIREBASE_MESSAGING_SENDER_ID
# - FIREBASE_APP_ID
# - FIREBASE_MEASUREMENT_ID (optional)

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create runtime config.json from secrets
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: 'config.json'
          json: |
            {
              "apiKey": "${{ secrets.FIREBASE_API_KEY }}",
              "authDomain": "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              "projectId": "${{ secrets.FIREBASE_PROJECT_ID }}",
              "storageBucket": "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              "messagingSenderId": "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              "appId": "${{ secrets.FIREBASE_APP_ID }}",
              "measurementId": "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
            }

      - name: Prepare deployment artifact
        run: |
          # Create the deployment directory and explicitly place the required files into it.
          # This is more robust than rsync as it avoids any .gitignore issues.
          mkdir -p _site
          cp index.html _site/
          # Rename config.json to a name not in .gitignore to ensure it's uploaded.
          mv config.json _site/firebase-config.json

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the dedicated build folder
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
