#!/bin/bash

# 1. Get the first 8 characters of the commit hash for brevity
VERSION_HASH=$(echo $GITHUB_SHA | cut -c1-8)

# 2. Get the current date/time to show when the build occurred
BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S %Z")

# 3. Use 'sed' to replace the placeholder in your file
# NOTE: The command syntax for sed might vary slightly depending on the runner OS (Linux/macOS).
sed -i "s|VERSION_COMMIT_HASH|${VERSION_HASH} (Built on: ${BUILD_DATE})|g" index.html

echo "Successfully injected version ${VERSION_HASH} into index.html"
