# 1. Add the workflow name (optional but recommended)
name: Deploy Application

# 2. Add the 'on' block to define triggers (MANDATORY)
on:
  # Trigger the workflow on a 'push' event
  push:
    # Only run if the push is to the 'main' branch
    branches:
      - main

# ----------------------------------------------------
# A workflow must have one or more jobs
# ----------------------------------------------------
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Calculate and Export Version Hash
        # The 'run' keyword executes the subsequent lines in the shell
        run: |
          # 1. Calculate the short hash locally in the shell script
          VERSION_HASH_TEMP=$(echo $GITHUB_SHA | cut -c1-8)
          
          # 2. Export the variable to the GitHub Actions Environment file ($GITHUB_ENV).
          echo "VERSION_HASH=$VERSION_HASH_TEMP" >> $GITHUB_ENV
          
          echo "Version Hash set to $VERSION_HASH_TEMP"

      - name: Deploy using the calculated hash
        run: |
          # The variable is now available as a global environment variable for the job
          echo "Starting deployment for version ${{ env.VERSION_HASH }}"
          
          # Replace this with your actual deployment command, e.g.:
          # docker push my-repo/my-app:${{ env.VERSION_HASH }}
          
          echo "Deployment successful."
