name: Auto-Version File
on:
  push:
    branches:
      - main
  # Allows manual triggering for testing
  workflow_dispatch: 

jobs:
  update_version:
    runs-on: ubuntu-latest
    # CRITICAL: Grant permission to push changes back
    permissions:
      contents: write 
      
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      # ------------------------------------------------------------------
      # STEP 1: Calculate and Set the Version Variable
      # ------------------------------------------------------------------
      - name: Calculate Short Hash
        id: version_hash
        run: |
          # Use GITHUB_SHA (the full commit hash) and cut it to 8 characters
          VERSION_SHORT_HASH=$(echo $GITHUB_SHA | cut -c1-8)
          echo "VERSION_HASH=$VERSION_SHORT_HASH" >> $GITHUB_ENV
          echo "Calculated Hash: $VERSION_SHORT_HASH"

      # ------------------------------------------------------------------
      # STEP 2: Replace the Placeholder in the File
      # ------------------------------------------------------------------
      - name: Replace Placeholder in File
        run: |
          # Use 'sed' to perform the in-place replacement
          # The custom delimiter '|' avoids issues if your hash contains '/'
          sed -i "s|VERSION_COMMIT_HASH|${{ env.VERSION_HASH }}|g" index.html
          
          echo "Updated index.html with version: ${{ env.VERSION_HASH }}"

      # ------------------------------------------------------------------
      # STEP 3: Commit and Push the change automatically
      # ------------------------------------------------------------------
      - name: Commit and Push updated index.html 🚀
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Specify the files you want to commit
          commit_message: "CI: Auto-update version in index.html to ${{ env.VERSION_HASH }}"
          files: index.html
          # Do not create a new workflow run from this automated commit
          commit_options: '--no-verify --allow-empty'
