# Deploy site to GitHub Pages and generate runtime config.json from repository secrets.
# Place your Firebase values in repository Secrets with the names below.
# Secrets required (create in repo Settings -> Secrets -> Actions):
# - FIREBASE_API_KEY
# - FIREBASE_AUTH_DOMAIN
# - FIREBASE_PROJECT_ID
# - FIREBASE_STORAGE_BUCKET
# - FIREBASE_MESSAGING_SENDER_ID
# - FIREBASE_APP_ID
# - FIREBASE_MEASUREMENT_ID (optional)

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create runtime config.json from secrets
        shell: bash
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          echo "Creating runtime config.json from secrets"
          # Use environment variables (populated from secrets) to avoid YAML interpolation issues
          cat > ./config.json <<EOF
{
  "apiKey": "${FIREBASE_API_KEY}",
  "authDomain": "${FIREBASE_AUTH_DOMAIN}",
  "projectId": "${FIREBASE_PROJECT_ID}",
  "storageBucket": "${FIREBASE_STORAGE_BUCKET}",
  "messagingSenderId": "${FIREBASE_MESSAGING_SENDER_ID}",
  "appId": "${FIREBASE_APP_ID}",
  "measurementId": "${FIREBASE_MEASUREMENT_ID}"
}
EOF

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload the repository root (adjust if your built site is in another folder)
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
