# ... (Previous steps for name, on, jobs, runs-on, and checkout)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Calculate and Export Version Hash
        id: version
        run: |
          # The variable is exported to the environment
          VERSION_HASH_TEMP=$(echo $GITHUB_SHA | cut -c1-8)
          echo "VERSION_HASH=$VERSION_HASH_TEMP" >> $GITHUB_ENV
          echo "Version Hash set to $VERSION_HASH_TEMP"

      - name: Replace Placeholder in index.html 🛠️
        # This step uses the shell 'sed' utility for in-place replacement
        run: |
          # 1. Define the variables for clarity
          VERSION="${{ env.VERSION_HASH }}"
          OLD_STRING="VERSION_PLACEHOLDER"
          FILE_PATH="index.html"
          
          echo "Replacing $OLD_STRING with $VERSION in $FILE_PATH"
          
          # 2. Execute sed command for in-place substitution
          # We use a custom delimiter like '|' to avoid conflicts with file paths or slashes in version hash
          # The 'g' flag ensures all occurrences are replaced (global)
          sed -i "s|$OLD_STRING|$VERSION|g" "$FILE_PATH"

      - name: Verify file change (Optional)
        run: cat index.html | grep ${{ env.VERSION_HASH }} # Should show the new hash

      - name: Deploy using the modified file
        run: |
          echo "Starting deployment for version ${{ env.VERSION_HASH }} with modified index.html"
          # Your actual deployment command here (e.g., docker push, deploy to S3, etc.)
          echo "Deployment successful."
