# Deploy site to GitHub Pages and generate runtime config.json from repository secrets.
# Place your Firebase values in repository Secrets with the names below.
# Secrets required (create in repo Settings -> Secrets -> Actions):
# - FIREBASE_API_KEY
# - FIREBASE_AUTH_DOMAIN
# - FIREBASE_PROJECT_ID
# - FIREBASE_STORAGE_BUCKET
# - FIREBASE_MESSAGING_SENDER_ID
# - FIREBASE_APP_ID
# - FIREBASE_MEASUREMENT_ID (optional)

name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare deployment artifact by injecting secrets
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        run: |
          mkdir -p _site
          # Use sed with -r for extended regex. Replace the placeholder *including* its quotes with the secret *including* new quotes.
          sed -r -e "s|\"__FIREBASE_API_KEY__\"|\"${FIREBASE_API_KEY}\"|g" \
              -e "s|\"__FIREBASE_AUTH_DOMAIN__\"|\"${FIREBASE_AUTH_DOMAIN}\"|g" \
              -e "s|\"__FIREBASE_PROJECT_ID__\"|\"${FIREBASE_PROJECT_ID}\"|g" \
              -e "s|\"__FIREBASE_STORAGE_BUCKET__\"|\"${FIREBASE_STORAGE_BUCKET}\"|g" \
              -e "s|\"__FIREBASE_MESSAGING_SENDER_ID__\"|\"${FIREBASE_MESSAGING_SENDER_ID}\"|g" \
              -e "s|\"__FIREBASE_APP_ID__\"|\"${FIREBASE_APP_ID}\"|g" \
              -e "s|\"__FIREBASE_MEASUREMENT_ID__\"|\"${FIREBASE_MEASUREMENT_ID}\"|g" \
              index.html > _site/index.html
          
          # Create a placeholder favicon to prevent 404 errors in the browser console
          echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2 2"><circle cx="1" cy="1" r="1" fill="#3b82f6"/></svg>' > _site/favicon.ico

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the dedicated build folder
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
